// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using siekskul.Data;

#nullable disable

namespace siekskul.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819060943_AddTableToDb")]
    partial class AddTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("siekskul.Models.Ekstrakurikuler", b =>
                {
                    b.Property<int>("EkstrakurikulerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EkstrakurikulerId"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuruId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EkstrakurikulerId");

                    b.HasIndex("GuruId");

                    b.ToTable("Ekstrakurikuler");
                });

            modelBuilder.Entity("siekskul.Models.Guru", b =>
                {
                    b.Property<int>("GuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuruId"));

                    b.Property<string>("Agama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidangEkstrakurikuler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NIP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GuruId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gurus");
                });

            modelBuilder.Entity("siekskul.Models.JadwalEkstrakurikuler", b =>
                {
                    b.Property<int>("JadwalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JadwalId"));

                    b.Property<int>("EkstrakurikulerId")
                        .HasColumnType("int");

                    b.Property<int>("Hari")
                        .HasColumnType("int");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WaktuMulai")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WaktuSelesai")
                        .HasColumnType("time");

                    b.HasKey("JadwalId");

                    b.HasIndex("EkstrakurikulerId");

                    b.ToTable("JadwalEkstrakurikuler");
                });

            modelBuilder.Entity("siekskul.Models.PendaftaranEkstrakurikuler", b =>
                {
                    b.Property<int>("PendaftaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PendaftaranId"));

                    b.Property<int>("EkstrakurikulerId")
                        .HasColumnType("int");

                    b.Property<int>("SiswaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalPendaftaran")
                        .HasColumnType("datetime2");

                    b.HasKey("PendaftaranId");

                    b.HasIndex("EkstrakurikulerId");

                    b.HasIndex("SiswaId");

                    b.ToTable("PendaftaranEkstrakurikuler");
                });

            modelBuilder.Entity("siekskul.Models.Siswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiswaId"));

                    b.Property<string>("Agama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kelas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NIS")
                        .HasColumnType("int");

                    b.Property<string>("NamaAyah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaIbu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SiswaId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Siswas");
                });

            modelBuilder.Entity("siekskul.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("siekskul.Models.Ekstrakurikuler", b =>
                {
                    b.HasOne("siekskul.Models.Guru", "Guru")
                        .WithMany("Ekstrakurikuler")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guru");
                });

            modelBuilder.Entity("siekskul.Models.Guru", b =>
                {
                    b.HasOne("siekskul.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("siekskul.Models.Guru", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("siekskul.Models.JadwalEkstrakurikuler", b =>
                {
                    b.HasOne("siekskul.Models.Ekstrakurikuler", "Ekstrakurikuler")
                        .WithMany("Jadwal")
                        .HasForeignKey("EkstrakurikulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekstrakurikuler");
                });

            modelBuilder.Entity("siekskul.Models.PendaftaranEkstrakurikuler", b =>
                {
                    b.HasOne("siekskul.Models.Ekstrakurikuler", "Ekstrakurikuler")
                        .WithMany("Pendaftaran")
                        .HasForeignKey("EkstrakurikulerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("siekskul.Models.Siswa", "Siswa")
                        .WithMany("PendaftaranEkstrakurikuler")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ekstrakurikuler");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("siekskul.Models.Siswa", b =>
                {
                    b.HasOne("siekskul.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("siekskul.Models.Siswa", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("siekskul.Models.Ekstrakurikuler", b =>
                {
                    b.Navigation("Jadwal");

                    b.Navigation("Pendaftaran");
                });

            modelBuilder.Entity("siekskul.Models.Guru", b =>
                {
                    b.Navigation("Ekstrakurikuler");
                });

            modelBuilder.Entity("siekskul.Models.Siswa", b =>
                {
                    b.Navigation("PendaftaranEkstrakurikuler");
                });
#pragma warning restore 612, 618
        }
    }
}
